version: '3.8'
x-restart-policy: &restart-policy
  restart: unless-stopped
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: "100m"
      max-file: "15"
x-network: &network
  networks:
    - rust

services:
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    <<: *restart-policy
    <<: *logging
    <<: *network
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=admin

networks:
  rust:
